apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  selector:
    app: mysql  # Cela doit correspondre au label utilisé dans votre Deployment
  ports:
  - port: 3306         # Le port MySQL exposé à l'intérieur du cluster
    targetPort: 3306   # Le port sur lequel le conteneur MySQL écoute
    nodePort: 30007    # Le NodePort explicite que vous souhaitez exposer

